name: Build docker container

on:
  push:
    branches: [ master, action-test ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - htslib_version: "1.14"
            bwa_version: "0.7.15"
          - htslib_version: "1.15.1"
            bwa_version: "0.7.15"
          - htslib_version: "1.15.1"
            bwa_version: "0.7.17"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build
        run: |
          docker build \
            --build-arg SAMTOOLS_VERSION=${{ matrix.config.htslib_version }} \
            --build-arg BCFTOOLS_VERSION=${{ matrix.config.htslib_version }}  \
            --build-arg HTSLIB_VERSION=${{ matrix.config.htslib_version }}  \
            --build-arg BWA_VERSION=${{ matrix.config.bwa_version }} \
            .
